### ISSUE TITLE
Rechte-System

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#6]
- [x] Mitglieder

  - [x] Jeder ist Mitglied #84
  - [x] Einsehen und Ändern der eigenen personenbezogenen Daten (z.B. Adresse, ...)
  - [x] Bestätigen der Datenschutzverordnung #35 
  - [x] Erteilen des Lastschriftmandats für den Abteilungsbeitrag #36 
- [x] Administratoren
  - [x] Alle Daten ändern und einsehen -> Wird in extra Issues geregelt

**Comment by TomasKostadinov** [comment]
Später kann über Gruppen usw nachgedacht werden

**Comment by DominikRuf** [comment]
Aufteilen in mehrere Issues zu jedem Model
